import React from 'react';

const DisclaimerPage: React.FC = () => {
  return (
    <div className="min-h-screen bg-gray-100 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white p-6 rounded-lg shadow-lg">
        <h1 className="text-3xl font-bold text-center mb-6 text-gray-800">Disclaimer</h1>

        <div className="space-y-6 text-gray-700">
          <section>
            <h2 className="text-xl font-semibold mb-2">Age Restriction</h2>
            <p>
              This product is intended for use by individuals aged 18 years or older. By accessing this service, you confirm that you are of legal age in your jurisdiction to view or generate NSFW content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Consent and Legal Use</h2>
            <p>
              You agree not to use this service to create, share, or distribute illegal content, including but not limited to child exploitation material, non-consensual imagery, or content that infringes on the rights of others. Any violation of this policy will result in immediate termination of access and may be reported to law enforcement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Disclaimer of Liability</h2>
            <p>
              The content generated by this AI is fictional and does not represent real individuals, events, or entities. The company is not responsible for how users generate, share, or use the content. Users assume full responsibility for their actions and any consequences that may arise.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Compliance with Laws</h2>
            <p>
              You are solely responsible for ensuring that your use of this service complies with all applicable laws and regulations in your jurisdiction. This service may not be available in certain regions due to legal restrictions.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Prohibition of Harmful or Offensive Content</h2>
            <p>
              You agree not to use this service to create content that promotes violence, hate speech, discrimination, or any other harmful or offensive behavior. Violations of this policy will result in immediate termination of access.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Ethical Use and Responsibility</h2>
            <p>
              We encourage the ethical and responsible use of this technology. Please consider the potential impact of the content you generate and strive to use this tool in a way that respects the rights and dignity of others.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Data Privacy and Security</h2>
            <p>
              Your privacy is important to us. We comply with applicable data protection laws, including the GDPR, to ensure your personal information is handled securely and responsibly. For more details, please review our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Right to Terminate Access</h2>
            <p>
              We reserve the right to terminate or restrict access to this service for any user who violates these terms of use or engages in inappropriate or illegal behavior.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">AI Limitations</h2>
            <p>
              This AI is trained to generate content based on user input, but it may produce unintended or inappropriate results. Users are advised to exercise caution and discretion when using this service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-2">Contact Information</h2>
            <p>
              If you encounter any content that violates these terms or applicable laws, please report it immediately to <a href="mailto:gavinli@animaai.cloud" className="text-blue-500 underline">gavinli@animaai.cloud</a>.
            </p>
          </section>
        </div>

        <div className="mt-8 text-center">
          <p className="text-sm text-gray-500">
            By using this service, you acknowledge that you have read, understood, and agree to this disclaimer.
          </p>
        </div>
      </div>
    </div>
  );
};

export default DisclaimerPage;